### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by HiCitron** [jeff06/CentrisApiHomeBrew#1]
This is so cool, seriously!

Did you use webscraping on the http get or do you have access to something else to extract this?

I was litterally building the same thing in Python right now

**Comment by jeff06** [comment]
Hi,

Thank you so much.
No, i just found the way to use their API route to get the data. Its in HTML, to i have to read it to convert it into an object.

Really! That really cool. If you need help with your project, let me know.

**Comment by HiCitron** [comment]
The API route? It does sound better.

I'm having trouble using  filters for the search because they aren't embedded in the URL (for instance 3 bedroom is a tag, and is not present in the URL).

How did you go around that? Do you wanna talk on discord or smth?

**Comment by jeff06** [comment]
Yeah Give me your discord, ill be more than happy to help you

**Comment by HiCitron** [comment]
iCitron#7248

**Comment by jeff06** [comment]
Added, hit me up when you are ready
